//Mostrar todos los usuarios
GET http://localhost:3000/users/

//Buscar un usuario en especifico
###
GET http://localhost:3000/users/3

### Crear nuevo usuario
POST http://localhost:3000/users/
Content-Type: application/json

{
    "username": "Laura",
    "password": "3012",
    "email": "Laura@gmail.com"
}

### Actualizar usuario
PUT http://localhost:3000/users/2
Content-Type: application/json

{
    "username": "Maria",
    "password": "1909",
    "email": "mariafer@gmail.com"
}

### Eliminar usuario
DELETE http://localhost:3000/users/4