//Mostrar todos los usuarios
GET http://localhost:3000/staff/

//Buscar un usuario en especifico
###
GET http://localhost:3000/staff/1

### Crear nuevo usuario
POST http://localhost:3000/staff/1
Content-Type: application/json

{
    "first_name": "Mario",
    "last_name": "Martinez",
    "birth_date": "1890-08-04",
    "gender": "M",
    "phone_number": "Martha",
    "email": "Martha@gmail.com",
    "address": "Monterrey",
    "is_active": true
}

### Actualizar usuario
PUT http://localhost:3000/staff/2
Content-Type: application/json

{
    "first_name": "Mario",
    "last_name": "Martinez",
    "birth_date": "1890-08-04",
    "gender": "M",
    "phone_number": "Martha",
    "email": "Martha@gmail.com",
    "address": "Monterrey",
    "is_active": true,
    //"user_id": 1
}

### Eliminar usuario
DELETE http://localhost:3000/staff/13