GET http://localhost:3000/usuarios

###
GET http://localhost:3000/usuarios/6

###
POST http://localhost:3000/usuarios/
content-type: application/json

{
    "nombre": "mari",
    "apellido": "Espiridion",
    "email": "mari.ad@gmail.com"
}