POST http://localhost:3000/auth/login 
Content-Type: application/json

{
"email": "saraespiridionbenequen@gmail.com", 
"password": "MyPassword"
}

### 
GET http://localhost:3000/users/protected 
Content-Type: application/json Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzMzOTQwMTMxLCJleHAiOjE3MzM5NDA0MzF9.qy9kZFHQkCDrJACTYTagT1OMPPwORQ1KcVH2nTZCeJ4
